### ISSUE TITLE
Enums as Types

### ISSUE THREAD

**Issue by that-hatter** [ProjectIgnis/scrapiyard#26]
Should Enums be usable as Types? e.g.:
```yml
parameters:
  - name: loc
    type: [ Location ]
    description: The location to check.
```
instead of using `int` and linking to the enum in the description:
```yml
parameters:
  - name: loc
    type: [ int ]
    description: The **Location** to check.
```

Pros:
* The allowed values are formalized. Helps static analyzers catch erroneous int values.
* No need to redundantly link to the enum in the description, especially if the enum's name gets mentioned more than once.

Cons:
* Could confuse people expecting an "enum" to represent all allowed values when used as a type. For example, in the case of the Location enum, you could actually pass a combination of `LOCATION_` constants, e.g. **LOCATION_MZONE|LOCATION_SZONE**.
